name: "ğŸš€ publish"

on: push
jobs:
  publish:
    name: ğŸš€ publish
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“š checkout
        uses: actions/checkout@v1
      - name: ğŸŸ¢ node
        uses: actions/setup-node@v1.4.2
         with:
          node-version: 10
          registry-url: https://registry.npmjs.org
      - run: npm install
      - name: ğŸš€ publish
        run: npm publish --access public
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
